.php70: &php70
  image: thedxw/php-testing:7.0

.phpunit: &phpunit
  before_script:
    - cd ${DIR}
    - composer install
  script:
    - vendor/bin/phpunit

.peridot: &peridot
  before_script:
    - cd ${DIR}
    - composer install
  script:
    - vendor/bin/peridot spec

.phpcsfixer: &phpcsfixer
  <<: *php70
  before_script:
    - cd ${DIR}
  script:
    - php-cs-fixer fix --dry-run -v --diff

.standardjs: &standardjs
  image: node:latest
  before_script:
    - cd ${DIR}
    - npm install -g standard
  script:
    - standard ${PATHS}

##############################################################################
### phpunit 7.0
##############################################################################

php70_themes_campaign-root:
  <<: *phpunit
  <<: *php70
  variables:
    DIR: wp-content/themes/campaign-root

##############################################################################
### peridot 7.0
##############################################################################

peridot70_themes_campaign-root:
  <<: *peridot
  <<: *php70
  variables:
    DIR: wp-content/themes/campaign-root

##############################################################################
### php-cs-fixer
##############################################################################

phplint_themes_campaign-root:
  <<: *phpcsfixer
  variables:
    DIR: wp-content/themes/campaign-root

##############################################################################
### standardJS
##############################################################################

standardjs_themes_campaign-root:
  <<: *standardjs
  variables:
    DIR: wp-content/themes/campaign-root
    PATHS: assets/js/*.js
