<?php

namespace Dxw\GdsCampaignRoot\Posts\CustomFieldGroups;

class ContentBlocks implements \Dxw\Iguana\Registerable
{
    public function register()
    {
        register_field_group(array(
            'key' => 'group_56e9937e4dc99',
            'title' => 'Content',
            'fields' => array(
                array(
                    'key' => 'field_572b3982eabf4',
                    'label' => 'Section',
                    'name' => 'content_blocks',
                    'type' => 'flexible_content',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => ''
                    ),
                    'button_label' => 'Add Section',
                    'min' => '',
                    'max' => '',
                    'layouts' => array(
                        // Banner
                        array(
                            'key' => '572b45ec7bc15',
                            'name' => 'banner',
                            'label' => 'Banner',
                            'display' => 'row',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_572c45dc7bc13',
                                    'label' => 'Title',
                                    'name' => 'title',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => ''
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                    'readonly' => 0,
                                    'disabled' => 0
                                ),
                                array(
                                    'key' => 'field_577a5dcc447fa',
                                    'label' => 'Caption',
                                    'name' => 'caption',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 0,
                                ),
                                array(
                                    'key' => 'field_57724adb499233',
                                    'label' => 'Button Text',
                                    'name' => 'button_text',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => '',
                                    'conditional_logic' => '',
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                    'readonly' => 0,
                                    'disabled' => 0,
                                ),
                                array(
                                    'key' => 'field_57724a9ffb445',
                                    'label' => 'Button URL',
                                    'name' => 'button_url',
                                    'type' => 'url',
                                    'instructions' => 'URL\'s should be written as the full domain. E.G. "http://www.example.com" or "https://www.example.com"',
                                    'required' => '',
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => 'http://www.example.com',
                                ),
                                array(
                                    'key' => 'field_577503ccb2790',
                                    'label' => 'GA Event tracking',
                                    'name' => 'ga_event_tracking',
                                    'type' => 'checkbox',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        'event_tracking' => 'Add Event Tracking',
                                    ),
                                    'default_value' => array(
                                    ),
                                    'layout' => 'vertical',
                                    'toggle' => 0,
                                ),
                                array(
                                    'key' => 'field_578504d141a44',
                                    'label' => 'Event Category',
                                    'name' => 'event_category',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => array(
                                        array(
                                            array(
                                                'field' => 'field_577503ccb2790',
                                                'operator' => '==',
                                                'value' => 'event_tracking',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        'External Link Clicked' => 'External Link Clicked',
                                        'Button Clicked' => 'Button Clicked',
                                        'Header Clicked' => 'Header Clicked',
                                    ),
                                    'default_value' => array(
                                    ),
                                    'allow_null' => 0,
                                    'multiple' => 0,
                                    'ui' => 0,
                                    'ajax' => 0,
                                    'placeholder' => '',
                                    'disabled' => 0,
                                    'readonly' => 0,
                                ),
                                array(
                                    'key' => 'field_571464645edf3',
                                    'label' => 'Background Image',
                                    'name' => 'background_image',
                                    'type' => 'file',
                                    'instructions' => 'Add a full width image here.',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => ''
                                    ),
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '1600 PX',
                                    'max_height' => '',
                                    'max_size' => '512 KB',
                                    'mime_types' => 'jpg,png',
                                ),
                                array(
                                    'key' => 'field_577a3a39d27a',
                                    'label' => 'Background Colour',
                                    'name' => 'background_colour',
                                    'type' => 'color_picker',
                                    'instructions' => 'If you don\'t want to use a full width image, set a background colour here.',
                                    'required' => '',
                                    'conditional_logic' => '',
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '#005ea5',
                                ),
                            ),
                            'min' => '',
                            'max' => ''
                        ),
                        // Heading
                        array(
                            'key' => '572b45dc7bc15',
                            'name' => 'heading',
                            'label' => 'Large Heading',
                            'display' => 'row',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_572b45dc7bc16',
                                    'label' => 'Title',
                                    'name' => 'title',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => ''
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                    'readonly' => 0,
                                    'disabled' => 0
                                ),
                                array(
                                    'key' => 'field_577a39f69d299',
                                    'label' => 'Customise',
                                    'name' => 'customise',
                                    'type' => 'checkbox',
                                    'instructions' => '',
                                    'required' => '',
                                    'conditional_logic' => '',
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        'yes' => 'Yes',
                                    ),
                                    'default_value' => array(
                                    ),
                                    'layout' => 'vertical',
                                    'toggle' => 0,
                                ),
                                array(
                                    'key' => 'field_8bcfa179764bb',
                                    'label' => 'Background Image',
                                    'name' => 'background_image',
                                    'type' => 'image',
                                    'instructions' => 'You can add images up to 512 KB in file size.',
                                    'required' => '',
                                    'conditional_logic' => array(
                                        array(
                                            array(
                                                'field' => 'field_577a39f69d299',
                                                'operator' => '==',
                                                'value' => 'yes',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                    'preview_size' => 'full',
                                    'library' => 'all',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '512 KB',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => 'jpg,png',
                                ),
                                array(
                                    'key' => 'field_e801e9b25ecee',
                                    'label' => 'Background Colour',
                                    'name' => 'background_colour',
                                    'type' => 'color_picker',
                                    'instructions' => '',
                                    'required' => '',
                                    'conditional_logic' => array(
                                        array(
                                            array(
                                                'field' => 'field_577a39f69d299',
                                                'operator' => '==',
                                                'value' => 'yes',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '#005ea5',
                                ),
                                array(
                                    'key' => 'field_59d95a4abf97a',
                                    'label' => 'Text Align',
                                    'name' => 'text_align',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => array(
                                        array(
                                            array(
                                                'field' => 'field_577a39f69d299',
                                                'operator' => '==',
                                                'value' => 'yes',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        'align-left' => 'Left',
                                        'align-centered' => 'Centered',
                                        'align-right' => 'Right',
                                    ),
                                    'default_value' => array(
                                        0 => 'left',
                                    ),
                                    'allow_null' => 0,
                                    'multiple' => 0,
                                    'ui' => 0,
                                    'ajax' => 0,
                                    'placeholder' => '',
                                    'disabled' => 0,
                                    'readonly' => 0,
                                ),
                                array(
                                    'key' => 'field_7461428f3a030',
                                    'label' => 'Text Colour',
                                    'name' => 'text_colour',
                                    'type' => 'color_picker',
                                    'instructions' => '',
                                    'required' => '',
                                    'conditional_logic' => array(
                                        array(
                                            array(
                                                'field' => 'field_577a39f69d299',
                                                'operator' => '==',
                                                'value' => 'yes',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '#ffffff',
                                ),
                            ),
                            'min' => '',
                            'max' => ''
                        ),
                        // Video Content
                        array(
                            'key' => '572c6183a937c',
                            'name' => 'video',
                            'label' => 'Video',
                            'display' => 'row',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_577a5dcc447eb',
                                    'label' => 'YouTube Video Link',
                                    'name' => 'video_link',
                                    'type' => 'text',
                                    'instructions' => 'Paste in the link to the YouTube video E.G. https://www.youtube.com/watch?v=YdsUunJAums',
                                    'required' => '',
                                    'conditional_logic' => '',
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                    'readonly' => 0,
                                    'disabled' => 0,
                                ),
                                array(
                                    'key' => 'field_577a39f69d499',
                                    'label' => 'Customise Background',
                                    'name' => 'customise_background',
                                    'type' => 'checkbox',
                                    'instructions' => '',
                                    'required' => '',
                                    'conditional_logic' => '',
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        'yes' => 'Yes',
                                    ),
                                    'default_value' => array(
                                    ),
                                    'layout' => 'vertical',
                                    'toggle' => 0,
                                ),
                                array(
                                    'key' => 'field_527b3a371d29d',
                                    'label' => 'Background Colour',
                                    'name' => 'background_colour',
                                    'type' => 'color_picker',
                                    'instructions' => '',
                                    'required' => '',
                                    'conditional_logic' => array(
                                        array(
                                            array(
                                                'field' => 'field_577a39f69d499',
                                                'operator' => '==',
                                                'value' => 'yes',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '#ffffff',
                                ),
                            ),
                            'min' => '',
                            'max' => ''
                        ),
                        // Text
                        array(
                            'key' => '572c6183a937a',
                            'name' => 'text',
                            'label' => 'Text',
                            'display' => 'row',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_577a5dcc447fb',
                                    'label' => 'Content',
                                    'name' => 'content',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 0,
                                ),
                                array(
                                    'key' => 'field_5741697a2fab4',
                                    'label' => 'Text Colour',
                                    'name' => 'text_colour',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => ''
                                    ),
                                    'choices' => array(
                                        'dark-text' => 'Dark',
                                        'light-text' => 'Light',
                                    ),
                                    'default_value' => array(
                                        0 => 'dark-text'
                                    ),
                                    'allow_null' => 0,
                                    'multiple' => 0,
                                    'ui' => 0,
                                    'ajax' => 0,
                                    'placeholder' => '',
                                    'disabled' => 0,
                                    'readonly' => 0
                                ),
                                array(
                                    'key' => 'field_577a39f69d410',
                                    'label' => 'Customise Background',
                                    'name' => 'customise_background',
                                    'type' => 'checkbox',
                                    'instructions' => '',
                                    'required' => '',
                                    'conditional_logic' => '',
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        'yes' => 'Yes',
                                    ),
                                    'default_value' => array(
                                    ),
                                    'layout' => 'vertical',
                                    'toggle' => 0,
                                ),
                                array(
                                    'key' => 'field_577a3a379d31a',
                                    'label' => 'Background Colour',
                                    'name' => 'background_colour',
                                    'type' => 'color_picker',
                                    'instructions' => '',
                                    'required' => '',
                                    'conditional_logic' => array(
                                        array(
                                            array(
                                                'field' => 'field_577a39f69d410',
                                                'operator' => '==',
                                                'value' => 'yes',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '#ffffff',
                                ),
                            ),
                            'min' => '',
                            'max' => ''
                        ),
                        // Left Align Image and Caption
                        array(
                            'key' => '572b4473b1181',
                            'name' => 'left_aligned_image',
                            'label' => 'Left-Aligned Image with Caption',
                            'display' => 'row',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_572b448cb1183',
                                    'label' => 'Image',
                                    'name' => 'image',
                                    'type' => 'image',
                                    'instructions' => 'You can add images up to 512 KB in file size.',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => ''
                                    ),
                                    'return_format' => 'array',
                                    'preview_size' => 'large',
                                    'library' => 'all',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '512 KB',
                                    'mime_types' => 'jpg,png'
                                ),
                                array(
                                    'key' => 'field_59d95a4abe97d',
                                    'label' => 'Image Size',
                                    'name' => 'image_size',
                                    'type' => 'select',
                                    'instructions' => 'A big image will take up half of the available area. A small image takes up a third of the available area.',
                                    'required' => 0,
                                    'conditional_logic' => '',
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        'default' => 'Big Image',
                                        'small-image' => 'Small Image',
                                    ),
                                    'default_value' => array(
                                        0 => 'default',
                                    ),
                                    'allow_null' => 0,
                                    'multiple' => 0,
                                    'ui' => 0,
                                    'ajax' => 0,
                                    'placeholder' => '',
                                    'disabled' => 0,
                                    'readonly' => 0,
                                ),
                                array(
                                    'key' => 'field_57724a9fcb438',
                                    'label' => 'Image URL',
                                    'name' => 'image_url',
                                    'type' => 'url',
                                    'instructions' => 'URL\'s should be written as the full domain including http or https E.G. "http://www.example.com" or "https://www.example.com"',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => 'http://www.example.com',
                                ),
                            ),
                            'min' => '',
                            'max' => ''
                        ),
                        // Right Align Image and Caption
                        array(
                            'key' => '572b44d4b1185',
                            'name' => 'right_aligned_image',
                            'label' => 'Right-Aligned Image with Caption',
                            'display' => 'row',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_572b44d4b1187',
                                    'label' => 'Image',
                                    'name' => 'image',
                                    'type' => 'image',
                                    'instructions' => 'You can add images up to 512 KB in file size.',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => ''
                                    ),
                                    'preview_size' => 'large',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '512 KB',
                                    'mime_types' => 'jpg,png',
                                    'return_format' => 'array',
                                    'library' => 'all'
                                ),
                                array(
                                    'key' => 'field_51a95a4abe97e',
                                    'label' => 'Image Size',
                                    'name' => 'image_size',
                                    'type' => 'select',
                                    'instructions' => 'A big image will take up half of the available area. A small image takes up a third of the available area.',
                                    'required' => 0,
                                    'conditional_logic' => '',
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        'default' => 'Big Image',
                                        'small-image' => 'Small Image',
                                    ),
                                    'default_value' => array(
                                        0 => 'default',
                                    ),
                                    'allow_null' => 0,
                                    'multiple' => 0,
                                    'ui' => 0,
                                    'ajax' => 0,
                                    'placeholder' => '',
                                    'disabled' => 0,
                                    'readonly' => 0,
                                ),
                                array(
                                    'key' => 'field_51724a9feb439',
                                    'label' => 'Image URL',
                                    'name' => 'image_url',
                                    'type' => 'url',
                                    'instructions' => 'URL\'s should be written as the full domain including http or https E.G. "http://www.example.com" or "https://www.example.com"',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => 'http://www.example.com',
                                ),
                            ),
                            'min' => '',
                            'max' => ''
                        ),
                        // Full Width Image
                        array(
                            'key' => '572b456ab118e',
                            'name' => 'full_width_image',
                            'label' => 'Full-width image',
                            'display' => 'row',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_572b456fb118f',
                                    'label' => 'Image',
                                    'name' => 'image',
                                    'type' => 'image',
                                    'instructions' => 'You can add images up to 512 KB in file size.',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => ''
                                    ),
                                    'return_format' => 'array',
                                    'preview_size' => 'large',
                                    'library' => 'all',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '512 KB',
                                    'mime_types' => 'jpg,png'
                                )
                            ),
                            'min' => '',
                            'max' => ''
                        ),
                        // Call to Action Banner
                        array(
                            'key' => '57724a89fb454',
                            'name' => 'call_to_action_banner',
                            'label' => 'Call to Action Banner',
                            'display' => 'row',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_57724a97fb428',
                                    'label' => 'Title',
                                    'name' => 'title',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => '1',
                                    'conditional_logic' => '',
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                    'readonly' => 0,
                                    'disabled' => 0,
                                ),
                                array(
                                    'key' => 'field_57724adb49901',
                                    'label' => 'Button Text',
                                    'name' => 'button_text',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => '1',
                                    'conditional_logic' => '',
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                    'readonly' => 0,
                                    'disabled' => 0,
                                ),
                                array(
                                    'key' => 'field_57724a9ffb429',
                                    'label' => 'Button URL',
                                    'name' => 'button_url',
                                    'type' => 'url',
                                    'instructions' => 'URL\'s should be written as the full domain including http or https E.G. "http://www.example.com" or "https://www.example.com"',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => 'http://www.example.com',
                                ),
                                array(
                                    'key' => 'field_577a39f69a296',
                                    'label' => 'Customise',
                                    'name' => 'customise',
                                    'type' => 'checkbox',
                                    'instructions' => '',
                                    'required' => '',
                                    'conditional_logic' => '',
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        'yes' => 'Yes',
                                    ),
                                    'default_value' => array(
                                    ),
                                    'layout' => 'vertical',
                                    'toggle' => 0,
                                ),
                                array(
                                    'key' => 'field_f219788a0f20a',
                                    'label' => 'Background Image',
                                    'name' => 'background_image',
                                    'type' => 'image',
                                    'instructions' => 'You can add images up to 512 KB in file size.',
                                    'required' => '',
                                    'conditional_logic' => array(
                                        array(
                                            array(
                                                'field' => 'field_577a39f69a296',
                                                'operator' => '==',
                                                'value' => 'yes',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                    'preview_size' => 'full',
                                    'library' => 'all',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '512 KB',
                                    'mime_types' => 'jpg,png'
                                ),
                                array(
                                    'key' => 'field_bfd182e264b5e',
                                    'label' => 'Background Colour',
                                    'name' => 'background_colour',
                                    'type' => 'color_picker',
                                    'instructions' => '',
                                    'required' => '',
                                    'conditional_logic' => array(
                                        array(
                                            array(
                                                'field' => 'field_577a39f69a296',
                                                'operator' => '==',
                                                'value' => 'yes',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '#005ea5',
                                ),
                                array(
                                    'key' => 'field_b3aac07896e62',
                                    'label' => 'Text Align',
                                    'name' => 'text_align',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => array(
                                        array(
                                            array(
                                                'field' => 'field_577a39f69a296',
                                                'operator' => '==',
                                                'value' => 'yes',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        'align-left' => 'Left',
                                        'align-centered' => 'Centered',
                                        'align-right' => 'Right',
                                    ),
                                    'default_value' => array(
                                        0 => 'left',
                                    ),
                                    'allow_null' => 0,
                                    'multiple' => 0,
                                    'ui' => 0,
                                    'ajax' => 0,
                                    'placeholder' => '',
                                    'disabled' => 0,
                                    'readonly' => 0,
                                ),
                                array(
                                    'key' => 'field_33cd8ea8dd160',
                                    'label' => 'Text Colour',
                                    'name' => 'text_colour',
                                    'type' => 'color_picker',
                                    'instructions' => '',
                                    'required' => '',
                                    'conditional_logic' => array(
                                        array(
                                            array(
                                                'field' => 'field_577a39f69a296',
                                                'operator' => '==',
                                                'value' => 'yes',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '#ffffff',
                                ),
                                array(
                                    'key' => 'field_577503aab2790',
                                    'label' => 'GA Event tracking',
                                    'name' => 'ga_event_tracking',
                                    'type' => 'checkbox',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        'event_tracking' => 'Add Event Tracking',
                                    ),
                                    'default_value' => array(
                                    ),
                                    'layout' => 'vertical',
                                    'toggle' => 0,
                                ),
                                array(
                                    'key' => 'field_577504d141a44',
                                    'label' => 'Event Category',
                                    'name' => 'event_category',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => array(
                                        array(
                                            array(
                                                'field' => 'field_577503aab2790',
                                                'operator' => '==',
                                                'value' => 'event_tracking',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        'External Link Clicked' => 'External Link Clicked',
                                        'Button Clicked' => 'Button Clicked',
                                        'Header Clicked' => 'Header Clicked',
                                    ),
                                    'default_value' => array(
                                    ),
                                    'allow_null' => 0,
                                    'multiple' => 0,
                                    'ui' => 0,
                                    'ajax' => 0,
                                    'placeholder' => '',
                                    'disabled' => 0,
                                    'readonly' => 0,
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        // Call to Action Button
                        array(
                            'key' => '57724a89fb427',
                            'name' => 'call_to_action_button',
                            'label' => 'Call to Action Button',
                            'display' => 'row',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_57724adb49913',
                                    'label' => 'Button Text',
                                    'name' => 'button_text',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => '1',
                                    'conditional_logic' => '',
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                    'readonly' => 0,
                                    'disabled' => 0,
                                ),
                                array(
                                    'key' => 'field_57524a9ffb449',
                                    'label' => 'Button URL',
                                    'name' => 'button_url',
                                    'type' => 'url',
                                    'instructions' => 'URL\'s should be written as the full domain including http or https E.G. "http://www.example.com" or "https://www.example.com"',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => 'http://www.example.com',
                                ),
                                array(
                                    'key' => 'field_578703aab2790',
                                    'label' => 'GA Event tracking',
                                    'name' => 'ga_event_tracking',
                                    'type' => 'checkbox',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        'event_tracking' => 'Add Event Tracking',
                                    ),
                                    'default_value' => array(
                                    ),
                                    'layout' => 'vertical',
                                    'toggle' => 0,
                                ),
                                array(
                                    'key' => 'field_598501e141a44',
                                    'label' => 'Event Category',
                                    'name' => 'event_category',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => array(
                                        array(
                                            array(
                                                'field' => 'field_578703aab2790',
                                                'operator' => '==',
                                                'value' => 'event_tracking',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        'External Link Clicked' => 'External Link Clicked',
                                        'Button Clicked' => 'Button Clicked',
                                        'Header Clicked' => 'Header Clicked',
                                    ),
                                    'default_value' => array(
                                    ),
                                    'allow_null' => 0,
                                    'multiple' => 0,
                                    'ui' => 0,
                                    'ajax' => 0,
                                    'placeholder' => '',
                                    'disabled' => 0,
                                    'readonly' => 0,
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        // Boxes
                        array(
                            'key' => 'field_5773c0d2bbc3c',
                            'label' => 'Boxes',
                            'name' => 'boxes',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => '',
                            'max' => '',
                            'layout' => 'row',
                            'button_label' => 'Add Row',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_5773c0ecbbc3d',
                                    'label' => 'Boxes',
                                    'name' => 'boxes',
                                    'type' => 'flexible_content',
                                    'instructions' => 'Flexible content boxes, these can contain images, text and call to actions or any combination of these. Shown across the width of the content area in groups of three.',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'button_label' => 'Add Item',
                                    'min' => 3,
                                    'max' => '',
                                    'layouts' => array(
                                        array(
                                            'key' => '5773c0f362bdc',
                                            'name' => 'box',
                                            'label' => 'Add Box',
                                            'display' => 'table',
                                            'sub_fields' => array(
                                                array(
                                                    'key' => 'field_5773c108bbc3e',
                                                    'label' => 'Title',
                                                    'name' => 'box_title',
                                                    'type' => 'text',
                                                    'instructions' => '',
                                                    'required' => 0,
                                                    'conditional_logic' => 0,
                                                    'wrapper' => array(
                                                        'width' => '',
                                                        'class' => '',
                                                        'id' => '',
                                                    ),
                                                    'default_value' => '',
                                                    'placeholder' => '',
                                                    'prepend' => '',
                                                    'append' => '',
                                                    'maxlength' => '',
                                                    'readonly' => 0,
                                                    'disabled' => 0,
                                                ),
                                                array(
                                                    'key' => 'field_577a5dcc447fd',
                                                    'label' => 'Caption',
                                                    'name' => 'box_caption',
                                                    'type' => 'textarea',
                                                    'instructions' => '',
                                                    'required' => 0,
                                                    'conditional_logic' => 0,
                                                    'wrapper' => array(
                                                        'width' => '',
                                                        'class' => '',
                                                        'id' => '',
                                                    ),
                                                    'default_value' => '',
                                                    'placeholder' => '',
                                                    'maxlength' => '',
                                                    'rows' => '',
                                                    'new_lines' => 'br',
                                                    'readonly' => 0,
                                                    'disabled' => 0,
                                                ),
                                                array(
                                                    'key' => 'field_5773c156bbc40',
                                                    'label' => 'Image',
                                                    'name' => 'box_image',
                                                    'type' => 'image',
                                                    'instructions' => 'You can add images up to 256 KB in file size. Images will be displayed above the title, caption and button',
                                                    'required' => 0,
                                                    'conditional_logic' => 0,
                                                    'wrapper' => array(
                                                        'width' => '',
                                                        'class' => '',
                                                        'id' => '',
                                                    ),
                                                    'return_format' => 'array',
                                                    'preview_size' => 'full',
                                                    'library' => 'all',
                                                    'min_width' => '',
                                                    'min_height' => '',
                                                    'min_size' => '',
                                                    'max_width' => '',
                                                    'max_height' => '',
                                                    'max_size' => '256 KB',
                                                    'mime_types' => 'jpg,png'
                                                ),
                                                array(
                                                    'key' => 'field_5773c148bbc42',
                                                    'label' => 'Button Text',
                                                    'name' => 'box_button_text',
                                                    'type' => 'text',
                                                    'instructions' => '',
                                                    'required' => 0,
                                                    'conditional_logic' => 0,
                                                    'wrapper' => array(
                                                        'width' => '',
                                                        'class' => '',
                                                        'id' => '',
                                                    ),
                                                    'default_value' => '',
                                                    'placeholder' => '',
                                                    'prepend' => '',
                                                    'append' => '',
                                                    'maxlength' => '',
                                                    'readonly' => 0,
                                                    'disabled' => 0,
                                                ),
                                                array(
                                                    'key' => 'field_5773c12abbc41',
                                                    'label' => 'Button URL',
                                                    'name' => 'box_button_url',
                                                    'type' => 'url',
                                                    'instructions' => 'URL\'s should be written as the full domain. E.G. "http://www.example.com" or "https://www.example.com"',
                                                    'required' => 0,
                                                    'conditional_logic' => 0,
                                                    'wrapper' => array(
                                                        'width' => '',
                                                        'class' => '',
                                                        'id' => '',
                                                    ),
                                                    'default_value' => '',
                                                    'placeholder' => 'http://www.example.com',
                                                ),
                                            ),
                                            'min' => '',
                                            'max' => '',
                                        ),
                                    ),
                                ),
                            ),
                        ),
                        // Statistic
                        array(
                            'key' => '5783776eabb7e',
                            'name' => 'statistic',
                            'label' => 'Statistic',
                            'display' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_5783777a6ff42',
                                    'label' => 'Statistic Data',
                                    'name' => 'statistic_data_value',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => '',
                                    'conditional_logic' => '',
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                    'readonly' => 0,
                                    'disabled' => 0,
                                ),
                                array(
                                    'key' => 'field_578377c76ff43',
                                    'label' => 'Statistic Description',
                                    'name' => 'statistic_data_value_description',
                                    'type' => 'textarea',
                                    'instructions' => '',
                                    'required' => '',
                                    'conditional_logic' => '',
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'maxlength' => '',
                                    'rows' => '',
                                    'new_lines' => '',
                                    'readonly' => 0,
                                    'disabled' => 0,
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        // Block Quote
                        array(
                            'key' => '578377756ff41',
                            'name' => 'block_quote',
                            'label' => 'Block Quote',
                            'display' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_57861e25d5cd4',
                                    'label' => 'Quote Text',
                                    'name' => 'quote_text',
                                    'type' => 'textarea',
                                    'instructions' => '',
                                    'required' => '',
                                    'conditional_logic' => '',
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'maxlength' => '',
                                    'rows' => '',
                                    'new_lines' => 'br',
                                    'readonly' => 0,
                                    'disabled' => 0,
                                ),
                                array(
                                    'key' => 'field_57861e34d5cd5',
                                    'label' => 'Quote Citation',
                                    'name' => 'quote_citation',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => '',
                                    'conditional_logic' => '',
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                    'readonly' => 0,
                                    'disabled' => 0,
                                ),
                                array(
                                    'key' => 'field_57861e44d5cd6',
                                    'label' => 'Citation URL',
                                    'name' => 'quote_citation_url',
                                    'type' => 'url',
                                    'instructions' => 'URL\'s should be written as the full domain. E.G. "http://www.example.com" or "https://www.example.com"',
                                    'required' => '',
                                    'conditional_logic' => '',
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => 'http://www.example.com',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        // Hidden Help Text
                        array(
                            'key' => '578683e09daad',
                            'name' => 'hidden_help_text',
                            'label' => 'Hidden Help Text',
                            'display' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_578684316746f',
                                    'label' => 'Summary',
                                    'name' => 'summary',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                    'readonly' => 0,
                                    'disabled' => 0,
                                ),
                                array(
                                    'key' => 'field_5786843f67470',
                                    'label' => 'Details',
                                    'name' => 'details',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 0,
                                ),
                                array(
                                    'key' => 'field_577a39f69d255',
                                    'label' => 'Customise Background',
                                    'name' => 'customise_background',
                                    'type' => 'checkbox',
                                    'instructions' => '',
                                    'required' => '',
                                    'conditional_logic' => '',
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        'yes' => 'Yes',
                                    ),
                                    'default_value' => array(
                                    ),
                                    'layout' => 'vertical',
                                    'toggle' => 0,
                                ),
                                array(
                                    'key' => 'field_577a3a379d291',
                                    'label' => 'Background Colour',
                                    'name' => 'background_colour',
                                    'type' => 'color_picker',
                                    'instructions' => '',
                                    'required' => '',
                                    'conditional_logic' => array(
                                        array(
                                            array(
                                                'field' => 'field_577a39f69d255',
                                                'operator' => '==',
                                                'value' => 'yes',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '#ffffff',
                                ),
                                array(
                                    'key' => 'field_5741697a1fca4',
                                    'label' => 'Text Colour',
                                    'name' => 'text_colour',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => array(
                                        array(
                                            array(
                                                'field' => 'field_577a39f69d255',
                                                'operator' => '==',
                                                'value' => 'yes',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => ''
                                    ),
                                    'choices' => array(
                                        'dark-text' => 'Dark',
                                        'light-text' => 'Light',
                                    ),
                                    'default_value' => array(
                                        0 => 'dark-text'
                                    ),
                                    'allow_null' => 0,
                                    'multiple' => 0,
                                    'ui' => 0,
                                    'ajax' => 0,
                                    'placeholder' => '',
                                    'disabled' => 0,
                                    'readonly' => 0
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                    )
                )
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'default',
                    ),
                ),
                array(
                    array(
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'page-content-blocks.php',
                    ),
                ),
                array(
                    array(
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'page-home.php',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => array(
                0 => 'custom_fields',
                1 => 'discussion',
                2 => 'comments',
                3 => 'send-trackbacks',
                4 => 'the_content'
            ),
            'active' => 1,
            'description' => ''
        ));
    }
}
