<?php

namespace Dxw\GdsCampaignRoot\Posts\CustomFieldGroups;

class Options implements \Dxw\Iguana\Registerable
{
    public function register()
    {
        if (function_exists('acf_add_options_sub_page')) {
            acf_add_options_sub_page('General');
            acf_add_options_sub_page('Error page');
        }

        if (function_exists('register_options_page')) {
            register_options_page('General');
        }

        if( function_exists('acf_add_local_field_group')) {
            acf_add_local_field_group(array (
            	'key' => 'group_5783ad387ba09',
            	'title' => 'Header Options',
            	'fields' => array (
            		array (
            			'key' => 'field_5783ad6ac8402',
            			'label' => 'Site Logo',
            			'name' => 'site_logo',
            			'type' => 'image',
            			'instructions' => 'The logo will take up no more than 25% of the space at the top of the page.',
            			'required' => 0,
            			'conditional_logic' => 0,
            			'wrapper' => array (
            				'width' => '',
            				'class' => '',
            				'id' => '',
            			),
            			'return_format' => 'array',
            			'preview_size' => 'full',
            			'library' => 'all',
            			'min_width' => '',
            			'min_height' => '',
            			'min_size' => '',
            			'max_width' => '',
            			'max_height' => '',
            			'max_size' => '',
            			'mime_types' => '',
            		),
            		array (
            			'key' => 'field_5783ad80c8403',
            			'label' => 'Header Background Image',
            			'name' => 'header_background_image',
            			'type' => 'file',
            			'instructions' => '',
            			'required' => 0,
            			'conditional_logic' => 0,
            			'wrapper' => array (
            				'width' => '',
            				'class' => '',
            				'id' => '',
            			),
            			'return_format' => 'array',
            			'library' => 'all',
            			'min_size' => '',
            			'max_size' => '',
            			'mime_types' => '',
            		),
            		array (
            			'key' => 'field_5783ada6c8404',
            			'label' => 'Header Background Colour',
            			'name' => 'header_background_colour',
            			'type' => 'color_picker',
            			'instructions' => 'Shows when no image is defined.',
            			'required' => 0,
            			'conditional_logic' => 0,
            			'wrapper' => array (
            				'width' => '',
            				'class' => '',
            				'id' => '',
            			),
            			'default_value' => '',
            		),
                    array (
            			'key' => 'field_5783ae6760319',
            			'label' => 'Footer Background Image',
            			'name' => 'footer_background_image',
            			'type' => 'image',
            			'instructions' => '',
            			'required' => 0,
            			'conditional_logic' => 0,
            			'wrapper' => array (
            				'width' => '',
            				'class' => '',
            				'id' => '',
            			),
            			'return_format' => 'array',
            			'preview_size' => 'full',
            			'library' => 'all',
            			'min_width' => '',
            			'min_height' => '',
            			'min_size' => '',
            			'max_width' => '',
            			'max_height' => '',
            			'max_size' => '',
            			'mime_types' => '',
            		),
            		array (
            			'key' => 'field_5783ae766031a',
            			'label' => 'Footer Background Colour',
            			'name' => 'footer_background_colour',
            			'type' => 'color_picker',
            			'instructions' => '',
            			'required' => 0,
            			'conditional_logic' => 0,
            			'wrapper' => array (
            				'width' => '',
            				'class' => '',
            				'id' => '',
            			),
            			'default_value' => '',
            		),
            		array (
            			'key' => 'field_5783adf460314',
            			'label' => 'Facebook ID',
            			'name' => 'facebook_id',
            			'type' => 'text',
            			'instructions' => '',
            			'required' => 0,
            			'conditional_logic' => 0,
            			'wrapper' => array (
            				'width' => '',
            				'class' => '',
            				'id' => '',
            			),
            			'default_value' => '',
            			'placeholder' => '',
            			'prepend' => '',
            			'append' => '',
            			'maxlength' => '',
            			'readonly' => 0,
            			'disabled' => 0,
            		),
            		array (
            			'key' => 'field_5783ae2260315',
            			'label' => 'Twitter ID',
            			'name' => 'twitter_id',
            			'type' => 'text',
            			'instructions' => '',
            			'required' => 0,
            			'conditional_logic' => 0,
            			'wrapper' => array (
            				'width' => '',
            				'class' => '',
            				'id' => '',
            			),
            			'default_value' => '',
            			'placeholder' => '',
            			'prepend' => '',
            			'append' => '',
            			'maxlength' => '',
            			'readonly' => 0,
            			'disabled' => 0,
            		),
            		array (
            			'key' => 'field_5783ae3160316',
            			'label' => 'Linkedin ID',
            			'name' => 'linkedin_id',
            			'type' => 'text',
            			'instructions' => '',
            			'required' => 0,
            			'conditional_logic' => 0,
            			'wrapper' => array (
            				'width' => '',
            				'class' => '',
            				'id' => '',
            			),
            			'default_value' => '',
            			'placeholder' => '',
            			'prepend' => '',
            			'append' => '',
            			'maxlength' => '',
            			'readonly' => 0,
            			'disabled' => 0,
            		),
            		array (
            			'key' => 'field_5783ae3b60317',
            			'label' => 'Google Tag Manager Code',
            			'name' => 'google_tag_manager_code',
            			'type' => 'textarea',
            			'instructions' => '',
            			'required' => 0,
            			'conditional_logic' => 0,
            			'wrapper' => array (
            				'width' => '',
            				'class' => '',
            				'id' => '',
            			),
            			'default_value' => '',
            			'placeholder' => '',
            			'maxlength' => '',
            			'rows' => '',
            			'new_lines' => '',
            			'readonly' => 0,
            			'disabled' => 0,
            		),
            		array (
            			'key' => 'field_5783ae4e60318',
            			'label' => 'Google Analytics Code',
            			'name' => 'google_analytics_code',
            			'type' => 'textarea',
            			'instructions' => '',
            			'required' => 0,
            			'conditional_logic' => 0,
            			'wrapper' => array (
            				'width' => '',
            				'class' => '',
            				'id' => '',
            			),
            			'default_value' => '',
            			'placeholder' => '',
            			'maxlength' => '',
            			'rows' => '',
            			'new_lines' => '',
            			'readonly' => 0,
            			'disabled' => 0,
            		),
            	),
            	'location' => array (
            		array (
            			array (
            				'param' => 'options_page',
            				'operator' => '==',
            				'value' => 'acf-options-general',
            			),
            		),
            	),
            	'menu_order' => 0,
            	'position' => 'normal',
            	'style' => 'default',
            	'label_placement' => 'top',
            	'instruction_placement' => 'label',
            	'hide_on_screen' => '',
            	'active' => 1,
            	'description' => '',
            ));

        }
    }
}
